# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171214_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=70),
        ),
    ]
